name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to varun-d-gl space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add varun https://varun-d-gl:$HF_TOKEN@huggingface.co/spaces/varun-d-gl/Recording-QC-Bot || true
          git push --force varun main

      - name: Push to product-ai-gl space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add product https://varun-d-gl:$HF_TOKEN@huggingface.co/spaces/product-ai-gl/Recording-QC-Bot || true
          git push --force product main
